name: Convert to Safari Extension
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and extract extension.zip
        run: |
          # Download extension.zip
          curl -LJO "https://nightly.link/Shared-Reality-Lab/IMAGE-browser/workflows/typescript-check/main/extension.zip"

          # Unzip the downloaded file
          unzip extension.zip -d build-chrome

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Update browserslist-db
        run: npx update-browserslist-db@latest

      - name: Install dependencies
        run: npm install

      - name: Extract background script filename
        id: extract_background_filename
        run: |
          background_script=$(jq -r '.background.service_worker' ./build-chrome/manifest.json)
          echo "$background_script" >> $GITHUB_STATE/background_script

      - name: Modify manifest.json
        run: |
          # Use the extracted filename to update the "scripts" field
          background_filename=$(cat $GITHUB_STATE/background_script)
          jq '.background = { scripts: [ $background_filename ], "type": "module" }' ./build-chrome/manifest.json > ./build-chrome/manifest.json.tmp
          mv ./build-chrome/manifest.json.tmp ./build-chrome/manifest.json

      - name: Convert to Safari extension
        run: xcrun safari-web-extension-converter ./build-chrome
