name: Convert to Safari Extension and Build Xcode Project
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build Chrome extension
        run: npm run pack:test
        
      - name: Extract background script filename
        id: extract_background_filename
        run: |
          background_script=$(jq -r '.background.service_worker' ./build-chrome/manifest.json)
          echo "$background_script" > extracted_background_script.txt
        
      - name: Modify manifest.json
        run: |
          # Use the extracted filename to update the "scripts" field
          background_filename=$(cat extracted_background_script.txt)
          jq --arg bf "$background_filename" '.background = { scripts: [ $bf ], "type": "module" }' ./build-chrome/manifest.json > ./build-chrome/manifest.json.tmp
          mv ./build-chrome/manifest.json.tmp ./build-chrome/manifest.json
        
      - name: Convert to Safari extension
        run: xcrun safari-web-extension-converter ./build-chrome
        
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
        
      - name: Build .app file
        run: xcodebuild -target "IMAGE Extension (Test)" -sdk "iphoneos" -configuration Release
        working-directory: IMAGE Extension (Test)
      